// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://loxnvlvlxocugrhogqim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxveG52bHZseG9jdWdyaG9ncWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzcwMjksImV4cCI6MjA2ODk1MzAyOX0.KERKMjMzMJgRsHbShcpYBkVbV82HWPTNrf_22fTszjU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});